### PR TITLE
pcn master load , countrylookup

### PR DESCRIPTION
**Pull request by martaschoch**
Added the code to load the countrylookup spreadsheet as an option in the pcn master, load command. This was missing in the original code I shared.

### CODE REVIEW

**Review by randrescastaneda — CHANGES_REQUESTED** [review]
Hi Marta, 

I am sorry, but I can't accept your pull request because your changes are made (or have been merged) to the changes made by David, which are also under revision. You need to create a separate branch from master, make your changes and then create the pull request. 

we can have a phone call to talk about it in case it is not clear. 
Thanks.

**Comment by martaschoch** [comment]
Hi Andres, thank you! can I reset my Marta branch to the master rather than create a new branch? or is the second preferred?

**Comment by randrescastaneda** [comment]
yes, you can reset your branch to the master branch.

**Comment by martaschoch** [comment]
Thanks Andres, I eventually created a new branch and sent you another pull request.

**Comment by randrescastaneda** [comment]
Excellent. Your pull request has been approved.

----------------------
R.Andrés Castañeda
Development Economics<https://www.worldbank.org/en/about/unit/unit-dec#2>, Data Group<https://data.worldbank.org/>/PovcalNet Team<http://iresearch.worldbank.org/PovcalNet/home.aspx>
The World Bank<https://www.worldbank.org/>|Washington, D.C.|+1 (202) 473-0108
MC 2-860<http://wbgmsmapq003.worldbank.org/bankquest/index2.php?id=MC2-860A&floorid=MC-02&auto=0>|WEBEX<https://worldbankgroup.webex.com/meet/pr1145171>|randrescastaneda.rbind.io<https://randrescastaneda.rbind.io/>

**Pull request closed without merging**
